baseURL = 'https://derya.io/'
languageCode = 'en-us'
title = 'Derya Yavuz Ionescu'
theme = 'PaperMod'
relativeurls = true
description = '''
Personal website for my portfolio & blog posts.
'''


[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/posts/"
  weight = 2

[params]
  [params.profileMode]
   enabled = true
   title = "Derya Yavuz Ionescu"
   subtitle = "Personal website for my portfolio & blog posts.."
   showPosts = true   

  [[params.socialIcons]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/derya-yavuz/"

  [[params.socialIcons]]
  name = "github"
  url  = "https://github.com/deryavuz1"


